version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/NGINX.dockerfile
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - webfiles:/app
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/PHP.dockerfile
    volumes:
      - webfiles:/app
  mysql:
    build:
      context: .
      dockerfile: dockerfiles/MYSQL.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - evote-mysqldata:/var/lib/mysql

volumes:
  webfiles:
  evote-mysqldata: